KMBBJ/KMBBJ_BACKEND

- backend/src/main/java/com/kmbbj/backend/global/config/properties/PropertyConfig.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/properties/docker-compose.yml
도커yml을 작성했으니 모두 이걸 사용해서 동일한 환경의 dp를 사용하기로함
propertyconfig을 사용해서 환경변수를 관리함
> 🔧	구성 파일 추가 : docker, yml

- backend/src/main/java/com/kmbbj/backend/global/config/properties/PropertyConfig.java
- backend/src/main/java/com/kmbbj/backend/global/config/redis/RedisConfig.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/properties/docker-compose.yml
> 🔀 Feature/redis redis 연결

- backend/src/main/java/com/kmbbj/backend/auth/entity/Authority.java
- backend/src/main/java/com/kmbbj/backend/auth/entity/User.java
- backend/src/main/java/com/kmbbj/backend/auth/repository/UserRespostiory.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/entity/redisToken.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/filter/TokenAuthenticationFilter.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/infrastructure/CustomUserDetails.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/infrastructure/JwtAuthenticationToken.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/repository/RedisTokenRepository.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/service/CustomUserDetailsService.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/service/TokenService.java
- backend/src/main/java/com/kmbbj/backend/global/config/jwt/util/JwtTokenizer.java
- backend/src/main/java/com/kmbbj/backend/global/config/security/SecurityConfig.java
> ✨ Feature/jwt : jwt 병합

- backend/build.gradle
- backend/src/main/java/com/kmbbj/backend/global/config/properties/EmailPropertyConfig.java
- backend/src/main/java/com/kmbbj/backend/global/config/redis/EmailRedisConfig.java
- backend/src/main/java/com/kmbbj/backend/notifications/config/MailConfig.java
- backend/src/main/java/com/kmbbj/backend/notifications/every_email_service/EveryEmailService.java
- backend/src/main/java/com/kmbbj/backend/notifications/properties/PropertyConfig.java
- backend/src/main/resources/application.yml
> ✨ 새 기능 : 이메일 발송 클래스 구현

- backend/src/main/java/com/kmbbj/backend/auth/entity/User.java
- backend/src/main/java/com/kmbbj/backend/auth/service/register/RegisterServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/global/config/redis/EmailRedisConfig.java
- backend/src/main/java/com/kmbbj/backend/global/config/security/SecurityConfig.java
- backend/src/main/java/com/kmbbj/backend/global/config/swagger/SwaggerConfig.java
- backend/src/main/resources/properties/docker-compose.yml
- backend/src/main/resources/sql/table/table.sql
> 🔀 Feature/swaggerendhotfix 

- backend/src/main/java/com/kmbbj/backend/notifications/entity/EmailAlarm.java
- backend/src/main/java/com/kmbbj/backend/notifications/every_email_service/EveryEmailService.java
- backend/src/main/java/com/kmbbj/backend/notifications/repository/EmailAlarmRepository.java
JavaMailSender를 주입받아 이메일 보내기 + 이메일 DB 저장 기능 추가
> 🎨기능 추가 : 이메일 발송 클래스 DB 저장 기능 추가

- backend/src/main/java/com/kmbbj/backend/notifications/loginemail/LoginEmailService.java
> 🎨기능 추가 : 회원가입용 이메일 발송 클래스

- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/CreateRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/RoomListDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/SearchingRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/SortConditionDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/SortedRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/Room.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/UserRoom.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/RoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/UserRoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/service/RoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/UserRoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/UserRoomServiceImpl.java
- backend/src/main/resources/sql/table/table.sql
> ✨ 새 기능 : 매칭 방 목록 정렬, 검색, 입장, 퇴장, 게임시작

- backend/src/main/java/com/kmbbj/backend/global/config/exception/ApiExceptionAdvice.java
- backend/src/main/java/com/kmbbj/backend/global/config/reponse/CustomResponse.java
- backend/src/main/java/com/kmbbj/backend/global/config/reponse/ErrorResponse.java
> ♻️ 코드 리팩토링 : 공통 응답, 예외 처리 분리

- backend/src/main/java/com/kmbbj/backend/global/config/authentication/AuthenticationPrincipalConfig.java
> ♻️ 코드 리팩토링 : 현재 유저 얻어내는 메서드 분리

- backend/src/main/java/com/kmbbj/backend/global/config/authentication/AuthenticationPrincipalConfig.java
Reverts KMBBJ/KMBBJ_BACKEND#40
> Revert "Revert "♻️ 코드 리팩토링 : 현재 유저 얻어내는 메서드 분리""

- backend/src/main/java/com/kmbbj/backend/balance/entity/AssetTransaction.java
- backend/src/main/java/com/kmbbj/backend/balance/entity/ChangeType.java
- backend/src/main/java/com/kmbbj/backend/balance/entity/TotalBalance.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/totalbalances/CustomTotalBalancesRepository.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/totalbalances/CustomTotalBalancesRepositoryImpl.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/totalbalances/TotalBalancesRepository.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/transaction/AssetTransactionRepository.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/transaction/CustomAssetTransactionRepository.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/transaction/CustomAssetTransactionRepositoryImpl.java
- backend/src/main/resources/sql/table/table.sql
> 🔀 Feature/total balances base : 자산 및 자산 변동 내역 

- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomServiceImpl.java
예외 및 주석 추가 했습니다.
랜덤 매칭 방 입장 수정했습니다.
빠른 입장 최소 인원 기준 수정했습니다.
> ♻️ 코드 리팩토링 : 예외 및 주석 추가

- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/EnterRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/RoomUserListDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/Room.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/UserRoom.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomServiceImpl.java
응답 데이터가 없어 프론트에서 방에 들어갔을때 현재 방에 있는 유저 목록을 띄워주지 않던 부분 수정.
matchingTask 와 assetRangeTask 가 작업이 완료되고 다른 작업들은 중지 되었는데도 계속 돌아가던 부분 수정.
> 🐛 버그 수정 : 응답을 보내주지 않던걸 enterRoomDto 로 보내주도록 수정

- backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameBalance.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameResult.java
- backend/src/main/java/com/kmbbj/backend/games/entity/Round.java
- backend/src/main/java/com/kmbbj/backend/games/entity/RoundResult.java
> ✨ feat: 엔티티 기능 추가했습니다

- backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
- backend/src/main/java/com/kmbbj/backend/games/dto/CurrentRoundDTO.java
- backend/src/main/java/com/kmbbj/backend/games/dto/GameStatusDTO.java
- backend/src/main/java/com/kmbbj/backend/games/dto/RoundResultDTO.java
- backend/src/main/java/com/kmbbj/backend/games/entity/Round.java
- backend/src/main/java/com/kmbbj/backend/games/entity/RoundResult.java
- backend/src/main/java/com/kmbbj/backend/games/repository/GameRepository.java
- backend/src/main/java/com/kmbbj/backend/games/repository/GameResultRepository.java
- backend/src/main/java/com/kmbbj/backend/games/repository/RoundRepository.java
- backend/src/main/java/com/kmbbj/backend/games/repository/RoundResultRepository.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameService.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundResultService.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundService.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/games/service/transaction/CoinSummaryService.java
- backend/src/main/java/com/kmbbj/backend/games/service/transaction/CoinSummaryServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- CurrentRoundDTO: 현재 게임 라운드의 상태를 나타내기 위한 DTO
- GameStatusDTO: 전체 게임의 상태를 추적하기 위한 DTO
- RoundResultDTO: 각 게임 라운드의 결과를 저장하기 위한 DTO
- GameRepository: 게임 엔티티의 CRUD 작업을 관리
- GameResultRepository: 게임 결과를 저장하고 조회하는 기능
- RoundRepository: 게임 라운드 데이터를 관리
- RoundResultRepository: 각 라운드의 결과를 저장하고 조회
- GameService: 게임의 주요 로직을 처리하는 서비스
- GameServiceImpl: GameService의 구체적인 구현 클래스
- RoundService: 각 라운드의 로직을 관리하는 서비스
- RoundServiceImpl: RoundService의 구체적인 구현 클래스
- CoinSummaryService: 게임 내 코인 관련 요약 정보를 관리하는 서비스
- CoinSummaryServiceImpl: CoinSummaryService의 구체적인 구현 클래스
> ✨ 새 기능 : 게임 서비스 로직 구현

- backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
- backend/src/main/java/com/kmbbj/backend/admin/entity/AdminAlarm.java
- backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
- backend/src/main/java/com/kmbbj/backend/auth/repository/UserRepository.java
- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
> ✨Feat: 관리자 유저 리스트 조회 기능 구현

- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/MatchingController.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
swagger 추가 및 주석 추가했습니다.
System.out.println 있던거 삭제 했습니다.
schduler 에 테스트를 위해 단위를 초로 해놨던걸 분으로 정상화 했습니다.
> ♻️ 코드 리팩토링 : swagger 추가 및 주석 추가

- backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameBalance.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameResult.java
- backend/src/main/java/com/kmbbj/backend/games/entity/Round.java
- backend/src/main/java/com/kmbbj/backend/games/entity/RoundResult.java
- backend/src/main/java/com/kmbbj/backend/games/enums/GameStatus.java
- backend/src/main/resources/sql/table/table.sql
🗃 데이버베이스 관련 수정 : gmae_balances  user_id BIGINT NOT NULL UNIQUE 추가 했습니다
> 💡 주석 추가/수정 : 엔티티 주석 설명 추가 넣었습니다.

- backend/src/main/resources/cql/create_keyspace.cql
- backend/src/main/resources/properties/docker-compose.yml
- backend/src/main/resources/properties/카산드라 선행 작업
> 🗃	데이버베이스 관련 수정 : 카산드라 docker가 안되서 명령어 통해서 해야할것 같음

- backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
- backend/src/main/java/com/kmbbj/backend/games/dto/CurrentRoundDTO.java
- backend/src/main/java/com/kmbbj/backend/games/dto/GameStatusDTO.java
- backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameBalance.java
- backend/src/main/java/com/kmbbj/backend/games/repository/GameRepository.java
- backend/src/main/java/com/kmbbj/backend/games/repository/RoundResultRepository.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameService.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundResultService.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/resources/sql/table/table.sql
게임 엔티티 , 게임 서비스 , 게임리퍼토지리 UUID 수정 
데이터 베이스도 수정
> ♻️ 코드 리펙토리:  게임 엔티티 , 게임 서비스 , 게임리퍼토지리 UUID 수정 

- backend/src/main/java/com/kmbbj/backend/games/controller/GameController.java
- backend/src/main/java/com/kmbbj/backend/games/dto/CurrentRoundDTO.java
- backend/src/main/java/com/kmbbj/backend/games/dto/GameStatusDTO.java
- backend/src/main/java/com/kmbbj/backend/games/entity/Game.java
- backend/src/main/java/com/kmbbj/backend/games/entity/GameBalance.java
- backend/src/main/java/com/kmbbj/backend/games/repository/GameRepository.java
- backend/src/main/java/com/kmbbj/backend/games/repository/RoundResultRepository.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameService.java
- backend/src/main/java/com/kmbbj/backend/games/service/game/GameServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundResultService.java
- backend/src/main/java/com/kmbbj/backend/games/service/round/RoundServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/resources/sql/table/table.sql
Reverts KMBBJ/KMBBJ_BACKEND#71
> Revert "♻️ 코드 리펙토리:  게임 엔티티 , 게임 서비스 , 게임리퍼토지리 UUID 수정 "

- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/TransactionController.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/AvailableBuyFundsRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/AvailableSellCoinsRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/CanselRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/OrderRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/TransactionsRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/request/UserAssetRequest.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/response/AvailableBuyFundsResponse.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/response/AvailableSellCoinsResponse.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/response/CoinAssetResponse.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/response/TransactionsResponse.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/controller/response/UserAssetResponse.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/repository/postgre/TransactionRepository.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/TransactionService.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/TransactionServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/buy/availablefunds/FindAvailableFunds.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/buy/availablefunds/FindAvailableFundsImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/execution/matching/ExecutionAllMatchingOrderImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/sell/availablecoinds/FindAvailableCoins.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/sell/availablecoinds/FindAvailableCoinsImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/findlist/FindTransactionsByUserId.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/findlist/FindTransactionsListByUserIdImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/finduserassetdetails/FindUserAssetDetails.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/finduserassetdetails/FindUserAssetDetailsImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/getlist/FindTransactionsByUserId.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/transaction/getlist/FindTransactionsListByUserIdImpl.java
- backend/src/main/java/com/kmbbj/backend/games/repository/CoinBalanceRepository.java
프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임프론트할꺼임
> ✨	새 기능 : 컨트롤러 생성! 이제프론트함

- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/java/com/kmbbj/backend/global/config/websocket/MatchWebSocketHandler.java
- backend/src/main/java/com/kmbbj/backend/global/config/websocket/WebSocketConfig.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/MatchingController.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/CreateRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/EditRoomDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/dto/RoomListDTO.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/Room.java
- backend/src/main/java/com/kmbbj/backend/matching/entity/StartSeedMoney.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/RoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/UserRoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/queue/MatchingQueueService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/queue/MatchingQueueServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/util/AssetRangeCalculator.java
- backend/src/main/resources/sql/table/table.sql
랜덤 , 빠른 매칭 수정했습니다.
StartSeedMoney 를 Long -> Enum 값으로 바꿨습니다.
방 수정 기능 구현했습니다.
> ♻️ 코드 리팩토링 : 랜덤 , 빠른 매칭 수정

- backend/src/main/java/com/kmbbj/backend/admin/controller/BalanceController.java
- backend/src/main/java/com/kmbbj/backend/admin/controller/RewardController.java
- backend/src/main/java/com/kmbbj/backend/admin/dto/AssetTransactionDTO.java
- backend/src/main/java/com/kmbbj/backend/admin/dto/RewardRequest.java
- backend/src/main/java/com/kmbbj/backend/admin/dto/UserBalanceAndTransactionsResponse.java
- backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
- backend/src/main/java/com/kmbbj/backend/admin/service/BalanceService.java
- backend/src/main/java/com/kmbbj/backend/admin/service/RewardService.java
- backend/src/main/java/com/kmbbj/backend/balance/entity/TotalBalance.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/transaction/AssetTransactionRepository.java
- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/resources/sql/table/table.sql
> Admin page

- backend/src/main/java/com/kmbbj/backend/charts/entity/kline/Kline.java
- backend/src/main/java/com/kmbbj/backend/charts/event/CoinUpdateEventListener.java
- backend/src/main/java/com/kmbbj/backend/charts/event/KlineScheduler.java
- backend/src/main/java/com/kmbbj/backend/charts/service/BinanceApiServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/charts/service/ChartServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/charts/service/CoinServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/repository/cassandra/buy/BuyOrderRepository.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/repository/cassandra/sell/SellOrderRepository.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/TransactionServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/execution/matching/ExecutionAllMatchingOrder.java
- backend/src/main/java/com/kmbbj/backend/feature/exchange/service/execution/matching/ExecutionAllMatchingOrderImpl.java
- backend/src/main/java/com/kmbbj/backend/games/entity/CoinBalance.java
코인 업데이트 시 이벤트를 발생시켜 들어와있는 매수 매도 주문을 체결한다.
> ✨ 새 기능 :  코인 업데이트 시 매수 매도 주문 체결

- backend/src/main/java/com/kmbbj/backend/global/sse/SseController.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseService.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/controller/RoomController.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/RoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/repository/UserRoomRepository.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/util/AssetRangeCalculator.java
- backend/src/main/java/com/kmbbj/backend/notifications/every_email_service/EveryEmailService.java
게임시작 버튼을 누른뒤 딜레이 시간 뒤에 시작하고, 안내메일 보내는 기능 추가
> ✨ 새 기능 : 게임시작 버튼을 누른뒤 딜레이 시간 뒤에 시작하고, 안내메일 보내는 기능 추가

- backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
- backend/src/main/java/com/kmbbj/backend/admin/controller/BalanceController.java
- backend/src/main/java/com/kmbbj/backend/admin/controller/RewardController.java
- backend/src/main/java/com/kmbbj/backend/admin/dto/RewardRequest.java
- backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
- backend/src/main/java/com/kmbbj/backend/admin/service/BalanceService.java
- backend/src/main/java/com/kmbbj/backend/admin/service/RewardService.java
- backend/src/main/java/com/kmbbj/backend/balance/repository/transaction/AssetTransactionRepository.java
> 🚑코드 정리 및 스웨거 적용 / 중복 url 수정

- backend/src/main/java/com/kmbbj/backend/global/config/exception/ExceptionEnum.java
- backend/src/main/java/com/kmbbj/backend/global/config/security/SecurityConfig.java
- backend/src/main/java/com/kmbbj/backend/global/sse/AdminDTO.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseService.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
> ✨ 새 기능 : 딜레이 후 게임시작 시 알림 기능 구현

- backend/src/main/java/com/kmbbj/backend/BackendApplication.java
- backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
- backend/src/main/java/com/kmbbj/backend/admin/controller/BalanceController.java
- backend/src/main/java/com/kmbbj/backend/admin/repository/AdminAlarmRepository.java
- backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
- backend/src/main/java/com/kmbbj/backend/global/sse/AdminDTO.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseController.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseServiceImpl.java
실시간 공지 백엔드 구현 + 유저 정지/해제할 경우 이메일 메서드 속도가 느려서 비동기 처리
> Admin/alarms✨ 관리자 실시간 공지 백엔드 구현, ⚡️ 유저 정지/해제 기능 비동기화 

- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/matching/MatchingServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/queue/MatchingQueueService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/queue/MatchingQueueServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomService.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/service/userroom/UserRoomServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/matching/util/AssetRangeCalculator.java
> ♻️ 코드 리팩토링 : 랜덤매칭 로직 수정

- backend/src/main/java/com/kmbbj/backend/admin/controller/AdminController.java
- backend/src/main/java/com/kmbbj/backend/admin/service/AdminService.java
- backend/src/main/java/com/kmbbj/backend/auth/entity/Authority.java
- backend/src/main/java/com/kmbbj/backend/auth/service/register/AdminRegisterService.java
- backend/src/main/java/com/kmbbj/backend/auth/service/register/AdminRegisterServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/auth/service/register/RegisterServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/global/config/security/SecurityConfig.java
- backend/src/main/java/com/kmbbj/backend/matching/service/room/RoomServiceImpl.java
- backend/src/main/resources/sql/table/table.sql
- backend/src/test/java/com/kmbbj/backend/auth/controller/UserControllerLogoutTest.java
[🗃 유저 권한 수정 + 관리자 회원가입 기능 추가](https://github.com/KMBBJ/KMBBJ_BACKEND/commit/02d0804729eebdd3f9107521efc9a8a66af09a5a)
> 🗃 유저 권한 수정 + 관리자 회원가입 기능 추가 

- backend/src/main/java/com/kmbbj/backend/admin/controller/AlarmsController.java
> 알람 조회 페이지 구현

- backend/src/main/java/com/kmbbj/backend/charts/service/BinanceApiServiceImpl.java
- backend/src/main/java/com/kmbbj/backend/charts/service/ChartServiceImpl.java
시간대별로 데이터를 받아오기 시작하는 startTime 변경하는 로직 추가
> ⚙️ 설정사항 수정: 달러 기준으로 저장하던 것 한국 환율로 변경,  interval 시간대별 로직 추가

- backend/src/main/java/com/kmbbj/backend/global/config/security/SecurityConfig.java
- backend/src/main/java/com/kmbbj/backend/global/sse/SseController.java
> 시큐리티/sse 오류 해결

- backend/src/main/java/com/kmbbj/backend/feature/matching/controller/MatchingController.java
- backend/src/main/java/com/kmbbj/backend/feature/matching/controller/RoomController.java
> ♻️ 코드 리팩토링 : swagger 예외처리 추가
